server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


  main:
    allow-circular-references: true


logging:
  level:
    ROOT: INFO
  file:
    name: transaction.log

